FROM nvcr.io/nvidia/tensorflow:25.02-tf2-py3

WORKDIR /workspace

COPY requirements-wsl-gpu.txt /tmp/requirements-wsl-gpu.txt
RUN python -m pip install --no-cache-dir -r /tmp/requirements-wsl-gpu.txt

EXPOSE 8888
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--no-browser", "--allow-root"]
